language: python
python:
  - "2.7"
cache: pip

env:
  - TRAVIS_NODE_VERSION="6"

before_install:
  # Install latest stable NodeJS version. Required for eslint.
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

before_script:
  - npm install

script:
  - "pylint video_xblock"
  - "eslint video_xblock/static/js/"
