language: python
python:
  - "2.7"
cache: pip

before_install:
  # Install latest stable NodeJS version. Required for eslint.
  - nvm install stable

before_script:
  - npm install eslint@"^3.13.0" eslint-config-edx@"^1.2.1"

script:
  - "pylint video_xblock"
  - "eslint video_xblock/static/js/"
